version: '3'

services:

  storage:
    build:
      context: ../../images/storage
      dockerfile: Dockerfile
      args:
        - IMAGE_TAG=${POSTGRES_TAG}
        - MAINTAINER_NAME=${MAINTAINER}
    network_mode: "host"

  backer:
    build:
      context: ../../images/backer
      dockerfile: Dockerfile      
      args:
        - IMAGE_TAG=${PYTHON_TAG}
        - MAINTAINER_NAME=${MAINTAINER}
    network_mode: "host"


  fronter:
    build:
      context: ../../images/fronter
      dockerfile: Dockerfile      
      args:
        - IMAGE_TAG=${NODE_TAG}
        - MAINTAINER_NAME=${MAINTAINER}
    network_mode: "host"