version: '3'

volumes:
  var_lib_postgresql_data:

networks:
  netmain:
    driver: bridge


services:

  storage:
    image: ${PROJECT}_storage
    expose:
      - "5432"
    ports:
      - "5432:5432"
    networks:
      - netmain
    volumes:
      - var_lib_postgresql_data:/var/lib/postgresql/data

  backer:
    image: ${PROJECT}_backer
    tty: true      
    networks:
      - netmain
    depends_on:
      - storage
    environment:
      - BASE_PROJECT=${PROJECT}
      - PROJECT=backer
      - PYTHONPATH=/usr/local/lib
      - WORKON_HOME=/usr/local/lib/${PROJECT}/backer/.env
      # ..
      - DJANGO_SETTINGS_MODULE=settings.dev
      - MIGRATE_MODE=true
      # ..
      - DB_NAME=${PROJECT}
      - DB_USER=${MAIN_POSTGRES_USER}
      - DB_PASSWORD=${MAIN_POSTGRES_PASSWORD}
      - DB_HOST=storage
      - DB_PORT=5432

    volumes:
      - ../../images/backer/src/:/usr/local/lib/${PROJECT}/backer
      - ../../images/backer/migrate.sh:/usr/local/bin/migrate.sh
    # ................
    command: /usr/local/bin/migrate.sh

