version: '3'

volumes:
  var_lib_postgresql_data:

networks:
  netmain:
    driver: bridge
   
services:

  storage:
    image: ${PROJECT}_storage
    expose:
      - "5432"
    ports:
      - "5432:5432"
    networks:
      - netmain
    volumes:
      - var_lib_postgresql_data:/var/lib/postgresql/data

  backer:
    image: ${PROJECT}_backer
    tty: true  
    # expose:
    #   - "8000"
    # ports:
    #   - "8000:8000"
    networks:
      - netmain
    depends_on:
      - storage
    environment:
      - BASE_PROJECT=${PROJECT}
      - PROJECT=backer
      - PYTHONPATH=/usr/local/lib
      - WORKON_HOME=/usr/local/lib/${PROJECT}/backer/.env
      # ..
      - DJANGO_SETTINGS_MODULE=settings.dev
      # ...
      - DB_NAME=${PROJECT}
      - DB_USER=${MAIN_POSTGRES_USER}
      - DB_PASSWORD=${MAIN_POSTGRES_PASSWORD}
      - DB_HOST=storage
      - DB_PORT=5432
    # ................
    volumes:
      - ../../images/backer/src/:/usr/local/lib/${PROJECT}/backer
      - ../../images/fronter/src/build:/usr/local/lib/${PROJECT}/fronter/build
      # ..
      - ../../images/backer/runserver.sh:/usr/local/bin/runserver.sh      
      # ..
    # ................
    command: /bin/bash

  fronter:
    image: ${PROJECT}_fronter
    tty: true    
    expose:
      - "3000"
    ports:
      - "3000:3000"
      - "3001:3001"
      - "9229:9229"
    networks:
      - netmain
    environment:
      - BASE_PROJECT=${PROJECT}      
      - PROJECT=fronter
      - BROWSERSYNC_PORT=3000
      - BROWSERSYNC_HOST=0.0.0.0
      - BROWSERSYNC_TARGET=http://backer:8000
    volumes:
      - ../../images/fronter/src/:/usr/local/lib/${PROJECT}/fronter
      - ../../images/fronter/runserver.sh:/usr/local/bin/runserver.sh      
    # ..............
    command: /bin/sh      